```{r}
#Brandon Rene Portillo Gonzalez
library(nycflights13)
library(tidyverse)
library(dplyr)
library(tidyr)

view(flights)
view(airports)
view(airlines)
view(planes)
view(weather)
```

```{r}
#1. Inner-Join
#1.1 Conecte fligts con planes


flights %>%
   inner_join(planes, by=c("tailnum"), suffix=c("_flights","_planes")) 
  
```
```{r}
#1.2
flights %>%
  inner_join(airlines, by=c("carrier"))
```
```{r}
#1.3
flights %>%
  inner_join(airports, by=c("origin"="faa"),suffix=c("_flights&p&a","_airports&origin"))%>%
  inner_join(airports, by=c("dest"="faa"),suffix=c("_flights&origin","_airports&dest"))
```
```{r}
#1.4
flights %>%
   inner_join(weather, by=c("year","month","day","hour","origin"))
```

```{r}
#2 Data manipulation

#2.1
flights %>%
  count(year,month,day) %>%
  filter(n > 1000) %>%
  arrange(desc(n))
```
```{r}
#2.2

flights_selected <-flights %>%
  select(year:day,hour,origin,dest,tailnum,carrier,arr_delay,dep_delay)
```

```{r}
#2.3
airlines %>%
  left_join(flights_selected,c("carrier"))%>%
  select(-origin,-dest) %>%
  mutate(tot_delay=arr_delay+dep_delay)
```
```{r .}
#2.4
precip_delay <- flights %>%
   inner_join(weather, by=c("year","month","day","hour","origin"))%>%
   group_by(precip) %>%
   summarise(mean_depdelay = mean(dep_delay,na.rm = TRUE)) %>%
   arrange(desc(mean_depdelay)) %>%
   mutate_at(c('mean_depdelay'), ~replace_na(.,0)) 
```
```{r}
#2.5
library(ggplot2)
ggplot(precip_delay, aes(x=precip, y=mean_depdelay)) + geom_point()
```
```{r}
#2.6
aux <- flights %>%
  filter(year==2013 & month==5 & day == 10) %>%
  group_by(dest) %>%
  summarise(delay=mean(arr_delay,na.rm=TRUE))

flight_airports <- airports %>%
  inner_join(aux,by=c("faa"="dest"))
```

```{r}
# 2.7
ggplot(flight_airports, aes(x=lon, y=lat, color=delay,size=delay)) + geom_point()

```

```{r}
#2.8
flights %>%
   inner_join(planes, by=c("tailnum"), suffix=c("_flights","_planes")) %>%
   transmute(tailnum,manufacturer,pi=(dep_delay+arr_delay)/air_time)
```

